import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { t } from './src/i18n';

@customElement('pdf-preview')
export class PdfPreview extends LitElement {
  @property({ type: Object }) data: any;

  static styles = css`
    .overlay {
      position: fixed;
      top: 0; left: 0; width: 100%; height: 100%;
      background: rgba(0,0,0,0.5);
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }
    .modal {
      background: white;
      padding: 20px;
      border-radius: 8px;
      max-width: 80%;
      max-height: 80%;
      overflow-y: auto;
      color: #333;
    }
    .printContent { padding: 20px; font-family: sans-serif; }
    .printContent table { width: 100%; border-collapse: collapse; }
    .printContent table th, .printContent table td { border: 1px solid #ccc; padding: 8px; text-align: left; }
    .actions { margin-top: 20px; display: flex; gap: 10px; }
  `;

  private close() {
    this.dispatchEvent(new CustomEvent('close'));
  }

  private download() {
    // @ts-ignore
    import('html2pdf.js').then((html2pdf) => {
        html2pdf.default().from(this.renderRoot.querySelector('.printContent')).save('SymptomSummary.pdf');
    });
  }

  render() {
    const { part, selectedSections, answers } = this.data;
    return html`
      <div class="overlay">
        <div class="modal">
          <div class="printContent">
            <h1>Symptom Summary</h1>
            <p>Body area examined: ${part.label} &middot; Generated for informational use only.</p>
            
            <h3>Selected sections</h3>
            <ul>
              ${selectedSections.map((s: string) => html`<li>${s}</li>`)}
            </ul>

            <h3>Responses</h3>
            <ul>
              <li><strong>How would you describe the pain or discomfort?:</strong> ${answers.painType}</li>
              <li><strong>How long has this been going on?:</strong> ${answers.duration}</li>
              <li><strong>How would you rate the severity?:</strong> ${answers.severity}</li>
            </ul>

            <h3>Possible specialists (ranked)</h3>
            <table>
              <thead><tr><th>#</th><th>Specialist</th><th>Confidence</th></tr></thead>
              <tbody>
                <tr><td>1</td><td>${t('orthopedist')}</td><td>50%</td></tr>
                <tr><td>2</td><td>${t('generalPractitioner')}</td><td>25%</td></tr>
              </tbody>
            </table>
            
            <p style="font-size: 12px; margin-top: 20px; color: #666; border: 1px solid #ccc; padding: 10px;">
              DISCLAIMER: I am not a doctor. This document was generated by an AI-based prediction tool for informational purposes only, based on self-reported answers. It is not a medical diagnosis. Always consult a licensed medical professional.
            </p>
          </div>
          <div class="actions">
            <button @click=${this.download}>Download PDF</button>
            <button @click=${this.close}>Cancel</button>
          </div>
        </div>
      </div>
    `;
  }
}
